### ISSUE TITLE
Cannot create file

### ISSUE THREAD

**Issue by bluemix** [netz-chat/objectdb#1]
the first thing I tried to run this code on my Flutter app
`
    final path = Directory.current.path + '/my.db';
`

i got this exception
`
FileSystemException: Cannot create file, path = '//my.db' (OS Error: Read-only file system, errno = 30)
`
is there any permission needs to be added before trying to create the database?

**Comment by MarioIM** [comment]
The file should be automatically created if the parent folder structure exists.
Please try to print and verify the `path` variable.
Are you using it with flutter? Then you should probably use the [path_provider](https://pub.dartlang.org/packages/path_provider) plugin with `getApplicationDocumentsDirectory()` to resolve the document-path corresponding to your app.

**Comment by bluemix** [comment]
yeah, sorry, I wasn't using path_provider plugin 👍
