### ISSUE TITLE
Insert locale-dependent document into db

### ISSUE THREAD

**Issue by stemuk** [netz-chat/objectdb#10]
I am currently trying to insert a different document into objectDb depending on the users locale.
In short, my code currently goes like: 
```
void main() async {
  // get document directory using path_provider plugin
  Directory appDocDir = await getApplicationDocumentsDirectory();

  String dbFilePath = [appDocDir.path, 'user.db'].join('/');

  // initialize and open database
  db = ObjectDB(dbFilePath);

  // delete old database file if exists
  File dbFile = File(dbFilePath);

  // check if database already exists
  var isNew = !await dbFile.exists();

  db.open();
  if (isNew) {
    //insert first document
    final document =
        r'[{"insert":"Welcome"}];
   db.insert({
      'document': document,
      'key': randomKey,
    });
  }
}
```
Now I am wondering: Is it possible to insert a different document into the db depending on the user devices locale? My first try was using `Localizations.localeOf(context);` which however didn't work because the `main()` function does not have a context. Is there any other way of achieving this? 

PS: Sorry for asking a simple question as an issue, I just didn't find any other place to ask. Thanks a lot for the awesome database! :+1:

**Comment by marioreggiori** [comment]
Check out the [objectdb_flutter example](https://github.com/netz-chat/objectdb_flutter/blob/master/example/lib/main.dart). You can insert data before returning the [root component](https://github.com/netz-chat/objectdb_flutter/blob/master/example/lib/main.dart#L102).

You could ask the question on StackOverflow ;)
& feel free to send me a pm via Twitter [@marioreggiori](https://twitter.com/marioreggiori) if i don't respond soon.

**Comment by marioreggiori** [comment]
Feel free to reopen if there are more questions related to this topic.
