### ISSUE TITLE
Is the the document inserting done desc or asc?

### ISSUE THREAD

**Issue by MichaelSowah** [netz-chat/objectdb#16]
If I insert a new document in my database which already has other documents will it insert it on top of the other documents or at the bottom?
if at the bottom, is there a way I can other my documents in desc when I fetch docs from db?

**Comment by marioreggiori** [comment]
Documents will be inserted at the bottom. 
For now you can't specify the fetching order. But you can do:
```dart
var reversed = result.reversed.toList();
```

**Comment by MichaelSowah** [comment]
ok, thanks works fine
