### ISSUE TITLE
first({}) gives Bad state: No element

### ISSUE THREAD

**Issue by JayendraGothi** [netz-chat/objectdb#18]
first function breaks with following message if there is no data in database: 

E/flutter ( 5223): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 5223): Bad state: No element
E/flutter ( 5223): #0      _ListBase&Object&ListMixin.firstWhere (dart:collection/list.dart:148:5)
E/flutter ( 5223): #1      ObjectDB._find.<anonymous closure> (package:objectdb/src/objectdb_base.dart:369:27)
E/flutter ( 5223): #2      new Future.sync (dart:async/future.dart:224:31)
E/flutter ( 5223): #3      ObjectDB._find (package:objectdb/src/objectdb_base.dart:363:19)
E/flutter ( 5223): <asynchronous suspension>
E/flutter ( 5223): #4      ObjectDB.first.<anonymous closure> (package:objectdb/src/objectdb_base.dart:480:50)
E/flutter ( 5223): #5      ExecutionQueue._check (package:execution_queue/execution_queue.dart:19:42)
E/flutter ( 5223): <asynchronous suspension>
E/flutter ( 5223): #6      ExecutionQueue._check (package:execution_queue/execution_queue.dart:21:12)
E/flutter ( 5223): <asynchronous suspension>
E/flutter ( 5223): #7      ExecutionQueue.add (package:execution_queue/execution_queue.dart:28:10)
E/flutter ( 5223): #8      ObjectDB.open (package:objectdb/src/objectdb_base.dart:35:33)

**Comment by marioreggiori** [comment]
What would you expect it to do?
Please use try/catch for this query.

**Comment by LaurentiuSimionescu** [comment]
This is kinda annoying. I would expect to find 

> {orElse: () => null}
