### ISSUE TITLE
Create 'Display as list example'

### ISSUE THREAD

**Issue by stemuk** [netz-chat/objectdb#2]
First of all thanks a lot for the database!
I would have one request for the documentation though: Would it be possible to add an example of how to query data from the database and add the results to a `Listview` widget? 
It is a relatively common pattern and adding it to the documentation would probably shorten up the adaptation time for objectdb.

**Comment by MarioIM** [comment]
Hey @stemuk, I hope you like it. :)
[Here](https://github.com/netz-chat/flutter_examples/blob/master/objectdb/listview/lib/main.dart) I've created a sample flutter project using ListView and ObjectDB.
Please tell me if it is useful or not.

**Comment by stemuk** [comment]
Awesome @MarioIM , exactly what I was looking for. Thanks a lot!
