### ISSUE TITLE
Generate list of subdocuments

### ISSUE THREAD

**Issue by stemuk** [netz-chat/objectdb#3]
This isn't really an issue, just me having a problem and no better place to ask the question :) 

I am currently implementing objectdb and created this test document: 
```
              {
                'cards': {'key01': {'question': 'buscar', 'answer': 'search'},'key02': {'question': 'tener', 'answer': 'have'} },
                'name': 'Spanish Vocabs',
              },
```
As you can see I tried to create a document with a subdocument named `cards`, that again has subdocuments that will have a randomly generated key ('key01' etc. in this example) as an identifier.

Now I would like to put all the subdocuments of `cards` into a `List [ ]` that I could pass on to another screen of the app. Is this possible with objectdb and if so, could you give me a hint on how to implement it?

**Comment by MarioIM** [comment]
I am not sure if I understand your question correctly.
Projection like in the MongoDB API isn't possible yet.
I haven't actually tested the following code.
But maybe you can use some of it.
```dart
var results = await db.find({'some':'filter'});

var cards = [];

for(var result in results){
  if(result.containsKey('cards') && result['cards'] is Map){
    for(var key in result['cards'].keys){
      cards.add(result['cards'][key]);
    }
  }
}

print(cards);
```
If it is a single result you can also do this:
```dart
var result = await db.first({'some':'filter'});

var cards = [];

if(result.containsKey('cards') && result['cards'] is Map){
  for(var key in result['cards'].keys){
    cards.add(result['cards'][key]);
  }
}

print(cards);
```

**Comment by stemuk** [comment]
Your code works exacly as I hoped! Thanks a lot! :+1:
