### ISSUE TITLE
Change delete() to remove() in the docs

### ISSUE THREAD

**Issue by stemuk** [netz-chat/objectdb#4]
As I implemented ObjectDB I noticed two minor issues. 
First, it seems to me that `db.delete({'active': false});` in the examples has become obsolete, and has been replaced by `db.remove({'active': false});`.  

Secondly I found it difficult to add subdocuments to an already existing doument, since the way to do it right now seems to be to `db.find()` the current subdocument, and then `db.update()` the parent document with `currentSubdocument.addAll(changes)`. In this case however `.addAll()` returns an error saying `The expression here has a type of 'void', and therefore cannot be used`. 

Adding `addToDocument()` would probably greatly simplify the process, or am I missing something here?

**Comment by MarioIM** [comment]
Oh thanks I'll fix that.

And I know that the updated functionality isn't perfect yet.
I want it to be similar to the MongoDB API.
I'll look into it as soo

**Comment by MarioIM** [comment]
Sorry I accidentally hit the close button ;)

**Comment by MarioIM** [comment]
Sorry, was very busy lately.
I just released an update including advanced updates.
Check out the [docs](https://github.com/netz-chat/objectdb#modify).
Example:
```dart
db.update({
  'age': RegExp('[18-20]'),
  Op.gt: {'duration': 500},
}, {
  Op.set: {"name.first": "Firstname"},
  Op.increment: {"stats.score", -10},
});
```
