### ISSUE TITLE
Remove failing and leaving artifacts in file

### ISSUE THREAD

**Issue by glweotek** [netz-chat/objectdb#67]
Hi,

I'm trying to remove a record. The query for the remove is the 'identity' attribute with the value: **7b612a09-8898-46cf-ae0c-8385e4899629** 

I'm getting this exception from the remove method:
	exception = {FormatException} FormatException: Unexpected character (at character 58)\n{"identity":"698b88d8-2857-4652-9b80-31fe2fa9cae0","em-{"identity":"7b61
 message = "Unexpected character"
 source = "{\"identity\":\"698b88d8-2857-4652-9b80-31fe2fa9cae0\",\"em-{\"identity\":\"7b612a09-8898-46cf-ae0c-8385e4899629\"}"
 offset = 57

This is what the database looks like before and after the remove(file):

BEFORE

$objectdb{"version":1,"client_version":1}
{"identity":"698b88d8-2857-4652-9b80-31fe2fa9cae0","email":"bf@gmail.com","notes":null,"name":{"first":"Bobby","last":"Flay"},"_id":"60ff0536b3183d9f3467ccb2"}
{"identity":"386993bf-d31d-4546-a07b-7b62f891e137","email":"bf@gmail.com","notes":null,"name":{"first":"Bobby","last":"Flay"},"_id":"60ff059840e29701d2942841"}
{"identity":"4482e911-6a7d-4923-b4c9-1c791db737d6","email":"bf@gmail.com","notes":null,"name":{"first":"Bobby","last":"Flay"},"_id":"60ff05fed671d2556759396a"}
{"identity":"**7b612a09-8898-46cf-ae0c-8385e4899629**","email":"bf@gmail.com","notes":null,"name":{"first":"Bobby","last":"Flay"},"_id":"60ff0ffa1e6ba7185717df4e"}
{"identity":"6f0fcb3d-cc67-4d61-8332-71b9cc4d3686","email":"bf@gmail.com","notes":null,"name":{"first":"Bobby","last":"Flay"},"_id":"60ff12393f8e62477a7bec59"}

AFTER
$objectdb{"version":1,"client_version":1}
{"identity":"698b88d8-2857-4652-9b80-31fe2fa9cae0","em-{"identity":"7b612a09-8898-46cf-ae0c-8385e4899629"}
by","last":"Flay"},"_id":"60ff0536b3183d9f3467ccb2"}
{"identity":"386993bf-d31d-4546-a07b-7b62f891e137","email":"bf@gmail.com","notes":null,"name":{"first":"Bobby","last":"Flay"},"_id":"60ff059840e29701d2942841"}
{"identity":"4482e911-6a7d-4923-b4c9-1c791db737d6","email":"bf@gmail.com","notes":null,"name":{"first":"Bobby","last":"Flay"},"_id":"60ff05fed671d2556759396a"}
{"identity":"7b612a09-8898-46cf-ae0c-8385e4899629","email":"bf@gmail.com","notes":null,"name":{"first":"Bobby","last":"Flay"},"_id":"60ff0ffa1e6ba7185717df4e"}
{"identity":"6f0fcb3d-cc67-4d61-8332-71b9cc4d3686","email":"bf@gmail.com","notes":null,"name":{"first":"Bobby","last":"Flay"},"_id":"60ff12393f8e62477a7bec59"}

You can see that the record with the identity '7b612a09-8898-46cf-ae0c-8385e4899629' has been removed, but a new record has been inserted into the file and this is what seems to be causing the exception listed above. 

I've seen something simular to this with the 'update' method, it left an artifact in the DB that a call to 'cleanup' fixed. This error is coming directly out of the ObjectDB remove method. I think this exception is masking something else, but I can't see what.

What's happening here? Can you provide the flow of what to expect? 

What's the cause of the 'added record' not being removed?

**Comment by marioreggiori** [comment]
The json document in the FormatException is invalid. Do you have multiple ObjectDB instances for one file at the same time? If so, you must only use a single/global instance (per DB file) for all of your queries.
If not, please provide some code to reproduce this error.

**Comment by glweotek** [comment]
Hi, I'll try to put together a program to replicate this issue. The json document in the exception is being added to the ObjectDB database by the database code, not by my code. It's added during the deletion of the record. It's the first record in the AFTER tag above. Like I noted above, I've seen this happen with other calls (update) where it leaves in the record that looks like a command structure. 'cleanup' fixes the other cases. Is it possible that the identity I'm using has characters being used internally by the DB?

**Comment by glweotek** [comment]
This is failing when I'm using it with the Bloc package. My test suite against objectDB directly works just fine. Same code in Bloc though does not, I'm getting the invalid json inserted into the DB. The only difference is that the database code is executed in the mapEventToState method vs inline. The remove is the only remaining issue, everything else works fine. I'll update this thread when I finish debugging this.

**Comment by jigarmistry** [comment]
I am trying to remove all documents by using following query.

`db.remove({});`

but getting below error 

```
E/flutter (28061): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FormatException: Unterminated string (at character 58)
E/flutter (28061): {"orderId":"T3JkZXJOb2RlOjE5MzU=","userId":"VXNlck5vZG-{}
E/flutter (28061):      
```

@marioreggiori

**Comment by marioreggiori** [comment]
@jigarmistry


> The json document in the FormatException is invalid. Do you have multiple ObjectDB instances for one file at the same time? If so, you must only use a single/global instance (per DB file) for all of your queries.
> If not, please provide some code to reproduce this error.

**Comment by glweotek** [comment]
Hi, Closing this issue. I have not resolved it and I am not going to spend anymore time trying to. The JSON input is valid, and if I execute the objectdb in pure Dart it works just fine. However, when I put it into a project using the Bloc library, it fails. The JSON is getting manipulated after it's input into ObjectDb for storage, and that JSON is invalid. But I cannot figure out how the original JSON is getting munged. It seems to be some interaction between the two libraries, but I cannot confirm that. The only difference in the code working or not is in the case it's not, is that the execution of the ObjectDB code is being directed by the Bloc library as to when it should execute. I don't have enough of a vested interest to continue debugging this, moving on.

**Comment by ali-1989** [comment]
I have the same problem, when I delete a record, I get this exception.
There seems to be a problem with JSON's composition when deleting the record.


when I try remove a record:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FormatException: Unexpected character (at character 58)
E/flutter ( 6219): {"Name":"AppSettings","Value":"{\"ChatNotificationEnab-{"Name":"AppSettings"}
```

**Comment by marioreggiori** [comment]
I still can't reproduce this error.
Without additional information (f.e. a small program which triggers this behavior), commenting on this issue does not achieve anything!

**Comment by ali-1989** [comment]
if I use `cleanup()` before `remove()` I get this exception.

**Comment by yh4922** [comment]
I will have this problem here too, 100% probability
As long as I call remove, an exception will be thrown, and the abnormal modification will remain in the file. After that, it cannot be read normally.

**Comment by yykou** [comment]
同样出现过该问题，而且一次异常后，其他的增删改查均会操作失败，必须卸载app重新安装
