### ISSUE TITLE
Unhandled Exception: FileSystemException: Cannot open file

### ISSUE THREAD

**Issue by 4RSIM3R** [netz-chat/objectdb#68]
**Describe the bug**
I have following documentation, and I have granted permission to access and write storage in my android device.
But, I am want to write some data and I had `Unhandled Exception: FileSystemException: Cannot open file` error, here is my code

```dart
class LocalDB {
  static final path = Directory.current.path + 'intiflex.db';

  ObjectDB get db => ObjectDB(FileSystemStorage(path));
}
```

```dart
final localDB = getIt<LocalDB>();
await localDB.db.insert(inspectionData);
```

**Comment by marioreggiori** [comment]
```dart
import 'package:path/path.dart' as p;

...

  static final path = p.join(Directory.current.path, 'intiflex.db');

...

```

**Comment by 4RSIM3R** [comment]
Hmmm, i have following your code, but I facing same error, there is my code :

```dart
import 'package:objectdb/objectdb.dart';
import 'package:objectdb/src/objectdb_storage_filesystem.dart';
import 'package:path/path.dart' as p;
import 'dart:io';


class LocalDB {
  static final path = p.join(Directory.current.path, 'intiflex.db');

  ObjectDB get db => ObjectDB(FileSystemStorage(path));
}
```

**Comment by m2faridi** [comment]
i have this problem in IOS 15

**Comment by marioreggiori** [comment]
@m2faridi `Directory.current.path` does not work on iOS. You need to use the [path_provider](https://pub.dev/packages/path_provider) plugin.

**Comment by m2faridi** [comment]
Please give a simple example

**Comment by marioreggiori** [comment]
You can find an example in the plugin docs
