### ISSUE TITLE
find by _id

### ISSUE THREAD

**Issue by dahayer** [netz-chat/objectdb#7]
I have a problem when finding objects by _id for example with this object i can find it with any key. hero, name item but not with _id sorry for my bad english :
"_id":"5a819757d3a28c13faa1fa39","hero":"Lesley","name":"top rank 5","item1":"Swift boots","item2":"Berserker's fury","item3":"Endless battle","item4":"Windtalker","item5":"Haass's claws","item6":"Immortality","__v":0}

**Comment by MarioIM** [comment]
The _id field has the type [ObjectId](https://pub.dartlang.org/packages/bson_objectid) internally.
For now you would need to use an ObjectId for querying.
This will change with the next update.

**Comment by dahayer** [comment]
thank you i will try to handle it.

**Comment by MarioIM** [comment]
The insert method returns an ObjectId.
If you want to `find`that id you have to transform this id back into a string by calling the toString() method on the id.

**Comment by dahayer** [comment]
Thank you for your help. problem solved :)
