### ISSUE TITLE
managing multiple documents from db

### ISSUE THREAD

**Issue by MichaelSowah** [netz-chat/objectdb#9]
Hi I Have two different documents in the db:
### **document 1**
 {
    "userData" : {
    "id":"16",
    "phone_number":"+233247832697",
    "first_name":"Michael",
    "last_name":"Sowah",
    "username":"mtsowah"
    }, 
    token: "9a647851935d03bbc87e25cef1bba0089efabcb1"
}

### **document 2**
{
    {
        "id":"1",
        "title":"Amazing! collection",
        "entity":"Amazing! collection","location":"Accra, Ghana",
        "description":"Amazingingly beautifull and quite affordable quality jeans..",
         "category":"Fashion",
         "type_id":"1",
         "reaction":"praise",
         "user_id":"2",
         "fullname":"James Bond",
         "username":"jamesbond007"
    },
    {
        "id":"2",
        "title":"collection",
        "entity":"Amazing! collection","location":"Accra, Ghana",
        "description":"Amazingingly beautifull and quite affordable quality jeans..",
         "category":"Fashion",
         "type_id":"1",
         "reaction":"praise",
         "user_id":"2",
         "fullname":"James Bond",
         "username":"jamesbond007"
    }
}

1. How do I get only document two from DB and how do I update and add more data/subdocuments to only document two when I want to?
2. How do I delete/remove document one only?

**Comment by MichaelSowah** [comment]
Thanks for the response.
from this example https://github.com/netz-chat/flutter_examples/blob/master/objectdb/listview/lib/main.dart

is it possible to have say eg:
`var data [
      {
        'name': {'first': 'Alex', 'last': 'Boyle'},
        'message': 'abc',
        'active': true
      },
      {
        'name': {'first': 'Maia', 'last': 'Herzog'},
        'message': 'def',
        'active': true
      },
      {
        'name': {'first': 'Curtis', 'last': 'Smith'},
        'message': 'ghi',
        'active': true
      },
      {
        'name': {'first': 'Jaquelin', 'last': 'Renner'},
        'message': 'jkl',
        'active': false
      },
      {
        'name': {'first': 'Denis', 'last': 'Swift'},
        'message': 'mno',
        'active': true
      },
      {
        'name': {'first': 'Anna', 'last': 'Metz'},
        'message': 'pqr',
        'active': true
      },
      {
        'name': {'first': 'Malinda', 'last': 'Reynolds'},
        'message': 'stu',
        'active': false
      },
    ];`
and then in 
`db.insertMany(data);`
is this possible? or how do I achieve something like this. Because my data coming from my server is formated something like this 
`{
        'name': {'first': 'Alex', 'last': 'Boyle'},
        'message': 'abc',
        'active': true
      },
      {
        'name': {'first': 'Maia', 'last': 'Herzog'},
        'message': 'def',
        'active': true
      },`

and I want to do db.insert with

**Comment by marioreggiori** [comment]
You have to wrap the response in json array brackets f.e.
```json
[{ 'name': {'first': 'Alex', 'last': 'Boyle'}, 'message': 'abc', 'active': true }, { 'name': {'first': 'Maia', 'last': 'Herzog'}, 'message': 'def', 'active': true }]
```
Now you can jsonDecode the string and insert the data with db.insertMany(data)

**Comment by MichaelSowah** [comment]
I get this error when I tried.
List<dynamic>' is not a subtype of type 'List<Map<dynamic, dynamic>>

**Comment by marioreggiori** [comment]
Could you please post the "print(data)" of the object you try to insert?

**Comment by MichaelSowah** [comment]
This is the decoded data from HTTP response.body, then I try to insert into db

`[{id: 12, title: , entity: Pizza Inn, location: Achimota, description: Chicken is awesome., category:
none, type_id: 1, reaction: null, user_id: 16, blob_id: 16, status: active, created_date: 2018-09-07 12:46:47, fullname:
Michael, username: mtsowah, yaip_blob_url: 1536346007_b64conv.jpg, yaip_type: Image, profile_picture_id: 5,
profile_picture: 1535715086_b64conv.jpg, praise_count: 1, shame_count: 0, comments_count: 0, category_list: 'none'},
{id: 9, title: , entity: Mothership LA | Serge Attukwei Clottey, location: La, Accra, description: Using his body as an
object Ghanaian artist Serge Attukwei Clottey works with international media - as well as plastic yellow "gallons"
(jerrycans) - to speak about politics, religion, sex and tradition., category: none, type_id: 1, reaction: shame,
user_id: 16, blob_id: 13, status: active, created_date: 2018-09-06 09:02:40, fullname: Michael, username: mtsowah,
yaip_blob_url: 1536246160_b64conv.jpg, yaip_type: Image, profile_picture_id: 5, profile_picture: 1535715086_b64.jpg, praise_count: 1, 
shame_count: 0, comments_count: 0, category_list: 'none'}]`

**Comment by marioreggiori** [comment]
Try something like this:
```dart
var data = List<Map<dynamic, dynamic>>.from(jsonDecode(jsonData));
db.insertMany(data);
```
